---
- name: Check if folder exists
  ansible.builtin.stat:
    path: "{{ dir_path | default(artifacts_folder) }}"
  register: directory_status

- name: Delete old folder
  ansible.builtin.file:
    state: absent
    path: "{{ dir_path | default(artifacts_folder) }}"
  when: directory_status.stat.exists
  become: true

- name: Create new directory
  ansible.builtin.file:
    state: directory
    path: "{{ dir_path | default(artifacts_folder) }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '775'
  become: true
